language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
  - node_modules

install:  
  - npm install
  - npm run lint
  - npm run build

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist/mtechVue
on:
  branch: master